"""initial

Revision ID: 3253d00015fe
Revises:
Create Date: 2026-04-23 15:36:57.096310
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3253d00015fe"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aliases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mention", sa.String(length=128), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aliases")),
        sa.UniqueConstraint("mention", "ticker", name="uq_alias_mention_ticker"),
    )
    with op.batch_alter_table("aliases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_aliases_mention"), ["mention"], unique=False)
        batch_op.create_index(batch_op.f("ix_aliases_ticker"), ["ticker"], unique=False)

    op.create_table(
        "kill_switch_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("activated", sa.Boolean(), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "trigger IN ('manual', 'env_var', 'drawdown', 'budget_llm', 'budget_twitterapi')",
            name=op.f("ck_kill_switch_events_trigger_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kill_switch_events")),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("avg_price_usd", sa.Float(), nullable=False),
        sa.Column("realized_pnl_usd", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_positions_symbol"), ["symbol"], unique=True)

    op.create_table(
        "raw_tweets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tweet_id", sa.String(length=64), nullable=False),
        sa.Column("x_user_id", sa.String(length=32), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_tweets")),
    )
    with op.batch_alter_table("raw_tweets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_raw_tweets_received_at"), ["received_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_raw_tweets_tweet_id"), ["tweet_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_raw_tweets_username"), ["username"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_tweets_x_user_id"), ["x_user_id"], unique=False)

    op.create_table(
        "risk_limits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("max_position_pct", sa.Float(), nullable=True),
        sa.Column("max_total_exposure_pct", sa.Float(), nullable=True),
        sa.Column("max_trades_per_day", sa.Integer(), nullable=True),
        sa.Column("max_daily_drawdown_pct", sa.Float(), nullable=True),
        sa.Column("allow_after_hours", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_limits")),
        sa.UniqueConstraint("strategy_id", "version", name="uq_risk_limit_strategy_version"),
    )
    with op.batch_alter_table("risk_limits", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_risk_limits_strategy_id"), ["strategy_id"], unique=False
        )

    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trading_mode", sa.String(length=16), nullable=False),
        sa.Column("paper_trading", sa.Boolean(), nullable=False),
        sa.Column("max_capital_usd", sa.Float(), nullable=False),
        sa.Column("max_position_pct", sa.Float(), nullable=False),
        sa.Column("max_total_exposure_pct", sa.Float(), nullable=False),
        sa.Column("max_trades_per_day", sa.Integer(), nullable=False),
        sa.Column("max_daily_drawdown_pct", sa.Float(), nullable=False),
        sa.Column("allow_after_hours", sa.Boolean(), nullable=False),
        sa.Column("llm_max_usd_per_day", sa.Float(), nullable=False),
        sa.Column("twitterapi_io_max_usd", sa.Float(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "trading_mode IN ('paper', 'live')", name=op.f("ck_settings_trading_mode_valid")
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_settings_singleton_row")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
    )
    op.create_table(
        "watched_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("x_user_id", sa.String(length=32), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watched_accounts")),
    )
    with op.batch_alter_table("watched_accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watched_accounts_username"), ["username"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_watched_accounts_x_user_id"), ["x_user_id"], unique=False
        )

    op.create_table(
        "llm_decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("raw_tweet_id", sa.Integer(), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("raw_response", sa.Text(), nullable=False),
        sa.Column("parsed_decision", sa.JSON(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('success', 'invalid_json', 'error')",
            name=op.f("ck_llm_decisions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_tweet_id"],
            ["raw_tweets.id"],
            name=op.f("fk_llm_decisions_raw_tweet_id_raw_tweets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_decisions")),
    )
    with op.batch_alter_table("llm_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_decisions_raw_tweet_id"), ["raw_tweet_id"], unique=False
        )

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("raw_tweet_id", sa.Integer(), nullable=False),
        sa.Column("llm_decision_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("intent", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("time_horizon", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "intent IN ('bullish', 'bearish', 'neutral', 'noise')",
            name=op.f("ck_events_intent_valid"),
        ),
        sa.CheckConstraint(
            "time_horizon IN ('intraday', 'swing', 'long')",
            name=op.f("ck_events_time_horizon_valid"),
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0", name=op.f("ck_events_confidence_in_unit")
        ),
        sa.ForeignKeyConstraint(
            ["llm_decision_id"],
            ["llm_decisions.id"],
            name=op.f("fk_events_llm_decision_id_llm_decisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raw_tweet_id"],
            ["raw_tweets.id"],
            name=op.f("fk_events_raw_tweet_id_raw_tweets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_event_id"), ["event_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_events_llm_decision_id"), ["llm_decision_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_events_raw_tweet_id"), ["raw_tweet_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_ticker"), ["ticker"], unique=False)

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("trading_mode", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("limit_price", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(order_type = 'limit' AND limit_price IS NOT NULL)"
            " OR (order_type = 'market' AND limit_price IS NULL)",
            name=op.f("ck_orders_limit_price_required_for_limit"),
        ),
        sa.CheckConstraint(
            "order_type IN ('market', 'limit')", name=op.f("ck_orders_order_type_valid")
        ),
        sa.CheckConstraint("side IN ('buy', 'sell')", name=op.f("ck_orders_side_valid")),
        sa.CheckConstraint(
            "trading_mode IN ('paper', 'live')", name=op.f("ck_orders_trading_mode_valid")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_orders_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_orders_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_orders_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_orders_external_id"), ["external_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_orders_idempotency_key"), ["idempotency_key"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_orders_symbol"), ["symbol"], unique=False)

    op.create_table(
        "rule_evaluations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("rule_priority", sa.Integer(), nullable=False),
        sa.Column("inputs_hash", sa.String(length=64), nullable=False),
        sa.Column("inputs_json", sa.JSON(), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("proposed_order_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('matched', 'skipped', 'failed')",
            name=op.f("ck_rule_evaluations_outcome_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_rule_evaluations_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_evaluations")),
    )
    with op.batch_alter_table("rule_evaluations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rule_evaluations_event_id"), ["event_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_rule_evaluations_rule_id"), ["rule_id"], unique=False)

    op.create_table(
        "fills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("external_fill_id", sa.String(length=128), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("commission_usd", sa.Float(), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("price > 0", name=op.f("ck_fills_price_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_fills_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_fills_order_id_orders"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fills")),
    )
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fills_external_fill_id"), ["external_fill_id"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_fills_filled_at"), ["filled_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_fills_order_id"), ["order_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_fills_symbol"), ["symbol"], unique=False)

    # ### end Alembic commands ###

    # --- INV-4: append-only triggers on audit tables -----------------------
    # SQLite syntax. Postgres port will use a BEFORE UPDATE/DELETE trigger
    # function returning NULL; migration will be dialect-branched then.
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        for table in (
            "llm_decisions",
            "rule_evaluations",
            "orders",
            "fills",
            "kill_switch_events",
        ):
            op.execute(
                f"""
                CREATE TRIGGER {table}_no_update
                BEFORE UPDATE ON {table}
                BEGIN
                    SELECT RAISE(ABORT, '{table} is append-only (INV-4)');
                END;
                """
            )
            op.execute(
                f"""
                CREATE TRIGGER {table}_no_delete
                BEFORE DELETE ON {table}
                BEGIN
                    SELECT RAISE(ABORT, '{table} is append-only (INV-4)');
                END;
                """
            )


def downgrade() -> None:
    # Drop triggers first — SQLite drops them with the table automatically,
    # but explicit DROPs keep the migration portable + idempotent.
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        for table in (
            "llm_decisions",
            "rule_evaluations",
            "orders",
            "fills",
            "kill_switch_events",
        ):
            op.execute(f"DROP TRIGGER IF EXISTS {table}_no_update")
            op.execute(f"DROP TRIGGER IF EXISTS {table}_no_delete")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fills_symbol"))
        batch_op.drop_index(batch_op.f("ix_fills_order_id"))
        batch_op.drop_index(batch_op.f("ix_fills_filled_at"))
        batch_op.drop_index(batch_op.f("ix_fills_external_fill_id"))

    op.drop_table("fills")
    with op.batch_alter_table("rule_evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rule_evaluations_rule_id"))
        batch_op.drop_index(batch_op.f("ix_rule_evaluations_event_id"))

    op.drop_table("rule_evaluations")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_symbol"))
        batch_op.drop_index(batch_op.f("ix_orders_idempotency_key"))
        batch_op.drop_index(batch_op.f("ix_orders_external_id"))
        batch_op.drop_index(batch_op.f("ix_orders_event_id"))

    op.drop_table("orders")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_ticker"))
        batch_op.drop_index(batch_op.f("ix_events_raw_tweet_id"))
        batch_op.drop_index(batch_op.f("ix_events_llm_decision_id"))
        batch_op.drop_index(batch_op.f("ix_events_event_id"))

    op.drop_table("events")
    with op.batch_alter_table("llm_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_decisions_raw_tweet_id"))

    op.drop_table("llm_decisions")
    with op.batch_alter_table("watched_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watched_accounts_x_user_id"))
        batch_op.drop_index(batch_op.f("ix_watched_accounts_username"))

    op.drop_table("watched_accounts")
    op.drop_table("settings")
    with op.batch_alter_table("risk_limits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_limits_strategy_id"))

    op.drop_table("risk_limits")
    with op.batch_alter_table("raw_tweets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_tweets_x_user_id"))
        batch_op.drop_index(batch_op.f("ix_raw_tweets_username"))
        batch_op.drop_index(batch_op.f("ix_raw_tweets_tweet_id"))
        batch_op.drop_index(batch_op.f("ix_raw_tweets_received_at"))

    op.drop_table("raw_tweets")
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_positions_symbol"))

    op.drop_table("positions")
    op.drop_table("kill_switch_events")
    with op.batch_alter_table("aliases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_aliases_ticker"))
        batch_op.drop_index(batch_op.f("ix_aliases_mention"))

    op.drop_table("aliases")
    # ### end Alembic commands ###
